Repository ably/ably-asset-tracking-swift, pull requests merged in 2022-09, with the labels that each got.

#354 Stop updating location immediately after stop command is issued
  Sources/AblyAssetTrackingPublisher/DefaultPublisher.swift
Labels: enhancement

#355 Start location only after the first trackable is added
  Sources/AblyAssetTrackingPublisher/DefaultPublisher.swift
Labels: code-quality

#356 Callback to success when an existing trackable is added
  Sources/AblyAssetTrackingPublisher/DefaultPublisher.swift
Labels: bug

#359 Reuse the add logic
  Sources/AblyAssetTrackingPublisher/DefaultPublisher.swift
Labels: code-quality

#379 Fix some incorrect conversions between milliseconds and seconds in the subscriber example app
  Examples/SubscriberExample/Sources/Screens/Map/MapViewController.swift
  README.md
Labels: bug
